### ISSUE TITLE
Adjusting font size is reversed

### ISSUE THREAD

**Issue by Kzer-Za** [Cactus64k/simple-fb2-reader#10]
Ctrl+WheelDown increases font size, Ctrl+WheelUp decreases it. Usually it's the other way around. At first, when Ctrl+WheelUp didn't work (it seems that the default font size is the smallest one), I thought the font size is not adjustable at all (there is nothing about the possibility of changing it in readme). If I didn't try Ctrl+WheelDown, I wouldn't know that it's adjustable at all :)

**Comment by Cactus64k** [comment]
In the "About" menu there is a description of hotkeys. I dont understand what you are proposing to do. The default font size is one. Do you need to do less than one? Or you want swap hotkeys for font size?

**Comment by Kzer-Za** [comment]
> Or you want swap hotkeys for font size?

This. Right now Ctrl+WheelDown increases font size, Ctrl+WheelUp decreases it. In all other programs Ctrl+WheelDown decreases font size, Ctrl+WheelUp increases it.

**Comment by Cactus64k** [comment]
Done. Use last commit.
