### ISSUE TITLE
An fb2.zip won't open

### ISSUE THREAD

**Issue by Kzer-Za** [Cactus64k/simple-fb2-reader#11]
I came across one particular fb2.zip file that Simple fb2 reader can't open for some reason. Other files in fb2.zip are opened without problems. If I extract fb2 from this zip-file, it also can be opened, so it is not corrupted fb2-file. I thought that it may be something with parameters of zip, so I extracted the fb2-file and tried packing it to zip with default parameters. The resulting file won't open.
Just to be clear: I'm perfectly fine with extracting it and reading the extracted file. Just thought I should let you know about this fact.
The file can be found at http://hpmor.ru/files/hpmor_ru.fb2.zip

**Comment by Cactus64k** [comment]
Try to use last commit.
