### ISSUE TITLE
Request: a capability to open somewhat broken fb2 files

### ISSUE THREAD

**Issue by Kzer-Za** [Cactus64k/simple-fb2-reader#15]
I came across an fb2 file that has something wrong with it (http://samlib.ru/k/kich_m_a/the_big_house.fb2.zip). Almost none of the fb2 readers that I have tried can open it, but coolreader (https://github.com/buggins/coolreader) can. I understand that if only one reader out of many can open it, then it means there is a problem with the file, and I understand if you don't want to waste your time on it, but it would be cool if Simple FB2 Reader could open such files.

**Comment by Cactus64k** [comment]
I'll look at your question in the code. Processing of internal FB2 data blocks was created in accordance with the format specification, so most likely the book file does not comply with the 2.1 standard.

**Comment by Cactus64k** [comment]
[the_big_house.fb2.zip](https://github.com/Cactus64k/simple-fb2-reader/files/12817090/the_big_house.fb2.zip)
There was an error in the book title, libxml is not able to parse such files
